[{
    "company_name":"tcs",
    "date":ISODate("2023-09-25"),
    "students_appeared":"shubham,vikash,raja,noyal,pratibha"
},
{
    "company_name":"hcl",
    "date":ISODate("2023-10-16"),
    "students_appeared":"abijit,sanjay,ebin,john,infant"
},
{
    "company_name":"wipro",
    "date":ISODate("2023-10-27"),
    "students_appeared":"virat,tammim,ashok,sri,king"
},
{
    "company_name":"zoho",
    "date":ISODate("2023-11-15"),
    "students_appeared":"naveen,suvan,felix,jethro,ashwin"
},
{
    "company_name":"guvi",
    "date":ISODate("2023-11-25"),
    "students_appeared":"jeshwin,jack,rohit,yogesh,edwin"
}]