[{
    "user_name":"shubham",
    "date":ISODate("2023-10-16"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"raja",
    "date":ISODate("2023-10-20"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"fernando",
    "date":ISODate("2023-10-29"),
    "attendance":"present",
    "task_submission":"passes"
},
{
    "user_name":"virat",
    "date":ISODate("2023-11-01"),
    "attendance":"absent",
    "task_submission":"passed"
},
{
    "user_name":"rohit",
    "date":ISODate("2023-11-16"),
    "attendance":"present",
    "task_submission":"failed"
},
{
    "user_name":"dhoni",
    "date":ISODate("2023-11-17"),
    "attendance":"present",
    "task_submission":"passed"
}]